The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
The “Crittenden Compromise,” as it became known, included six proposed constitutional amendments and four proposed Congressional resolutions that Crittenden hoped would appease Southern states and help the nation avoid civil war.
